apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "cert-manager-issuer.fullname" . }}
  labels:
    {{- include "cert-manager-issuer.labels" . | nindent 4 }}
spec:
  selfSigned: {}